### PR TITLE
update composer.json to suggest forked package

### PR DESCRIPTION
**Pull request by Dwarfex**
Hi @rkeet 

as you suggested, i forked your project and added a new Laminas Version.

Grretings,
Dwarfex

### CODE REVIEW

**Comment by rkeet** [comment]
Merging composer.json change for recommended alternative package

**Comment by rkeet** [comment]
Whoops, wrong button, now it's merged :p

**Comment by Dwarfex** [comment]
@rkeet Thanks :) - btw you might need to make a new relase to get this on packagist :)

**Comment by rkeet** [comment]
Hi, no problem. Thanks for continuing it! FeelsGoodMan that the package is wanted. 

Packagist had the latest version with the suggested package. Seems however not to automatically copy the suggested package in their notification. Added that in manually now, thanks for the heads up. 

If you're going to seriously pick up this package, I might suggest you have a look at this first PR done on this repo: https://github.com/rkeet/zf-doctrine-encrypt/pull/1

While I disagreed with adding that in, maybe a package extending this one for searchable encrypted properties is not a bad idea. 

Food for thought and gl & hf.

**Pull request merged**
